### ISSUE TITLE
 [Bug] Browser tab crashes on mouse drag out of window #9265 

### ISSUE THREAD

**Issue by felixpalmer** [visgl/mjolnir.js#7]
First [reported in deck.gl](https://github.com/visgl/deck.gl/issues/9265), when the mouse pointer is dragged outside the region controlled by Mjolnir the entire tab freezes. Can be reproduced on https://visgl.github.io/mjolnir.js/examples/event-manager

When I pause execution in dev tools it looks like the code has got itself into an infinite loop here: https://github.com/visgl/mjolnir.js/blob/master/src/hammerjs/utils/has-parent.ts (I tried running the code locally, but am getting build errors so I'm just following the minified code)

**Comment by Pessimistress** [comment]
3.0.0-beta.1
